name: release

on:
  create:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull, tag, and push App image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-app:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-app:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-app:${{ github.ref_name }}

      - name: Pull, tag, and push Caddy image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-caddy:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-caddy:latest ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-caddy:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-example-caddy:${{ github.ref_name }}
